name: Test action

on:
  workflow_dispatch:
    sample_input:
      description: Will be echoed
      type: string
      required: true


jobs:
  testing-stuff:
    name: It has a name now
    runs-on: ubuntu-latest

    steps:
      - name: Echo the input directly
        run: echo ${{ inputs.sample_input }}

      - name: Run the input directly
        run: ${{ inputs.sample_input }}

